/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AvatarAndSubtitList: typeof import('./src/components/lists/AvatarAndSubtitList.vue')['default']
    AvatarCard: typeof import('./src/components/cards/AvatarCard.vue')['default']
    BasicList: typeof import('./src/components/lists/BasicList.vue')['default']
    ChatList: typeof import('./src/components/lists/ChatList.vue')['default']
    CollapsibleList: typeof import('./src/components/lists/CollapsibleList.vue')['default']
    FancyCard: typeof import('./src/components/cards/FancyCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoCard: typeof import('./src/components/cards/InfoCard.vue')['default']
    Lists: typeof import('./src/components/lists/Lists.vue')['default']
    LoginCard: typeof import('./src/components/cards/LoginCard.vue')['default']
    MultiOptCard: typeof import('./src/components/cards/MultiOptCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectableList: typeof import('./src/components/lists/SelectableList.vue')['default']
  }
}
